services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/
      - static_data:/app/staticfiles
      - media_data:/app/media

  nginx:
    image: nginx:alpine
    container_name: main-nginx
    depends_on:
      main-app:
        condition: service_started
    ports:
      - "${DJANGO_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro

  celery-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A core.project worker --loglevel=info
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/

  celery-beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-beat
    command: celery -A core.project beat --loglevel=info
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/

volumes:
  static_data:
  media_data:
