services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${DJANGO_PORT}:8000"
    command: >
      sh -c "uv sync --locked && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/

  celery-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-worker
    command: >
      sh -c "uv sync --locked && celery -A core.project worker --loglevel=info"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/

  celery-beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-beat
    command: >
      sh -c "uv sync --locked && celery -A core.project beat --loglevel=info"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ..:/app/
