version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - ../.env

  redis:
    image: redis:latest
    container_name: metri-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: